### ISSUE TITLE
Allow inverting position status

### ISSUE THREAD

**Issue by burntcookie90** [QuickSander/homebridge-http-curtain#14]
I am trying to use this with shades that report `0` for `open`, but this plugin reports `0` as `closed` to homekit. Is it possible to get a checkbox for "Invert value" in the accessory config?

**Comment by QuickSander** [comment]
Hi, should be possible. Let me see what I can do this evening.

**Comment by QuickSander** [comment]
Are your shades returning '2' for idle?

**Comment by burntcookie90** [comment]
I don't believe so. According to [this](https://support.somasmarthome.com/hc/en-us/articles/360026064234-HTTP-API) the position is 0..100 (open..close).

**Comment by QuickSander** [comment]
Oh Oké, I understand you want to invert the actual position value instead of the state

**Comment by burntcookie90** [comment]
Ah yep! Sorry for the vague request at the top

**Comment by QuickSander** [comment]
Can you try if version 1.4.0 suits your needs?

**Comment by burntcookie90** [comment]
Works! Thank you for the quick turnaround!
