### ISSUE TITLE
Stuck on Opening...

### ISSUE THREAD

**Issue by iKrushYou** [QuickSander/homebridge-http-curtain#17]
Hey, I just set this plugin up and it seems I can't get things 100% (ha)

Here is my config
```
      {
            "name": "Office Blinds",
            "notificationID": "my-http-curtain",
            "getCurrentPosUrl": {
                "url": "http://192.168.1.53/api/status",
                "method": "GET"
            },
            "getPositionStateUrl": {
                "method": "GET"
            },
            "setTargetPosUrl": {
                "url": "http://192.168.1.53/api/position?pct=%d",
                "method": "PUT"
            },
            "getTargetPosUrl": {
                "method": "GET"
            },
            "identifyUrl": {
                "method": "GET"
            },
            "pullInterval": 5000,
            "accessory": "HttpCurtain"
        }
```

When the curtain is open, the status API returns
```
curl http://192.168.1.53/api/status 
100
```

Which is what I believe the plugin is expecting. When closed, it returns 0. When I tap the blinds card to close it, the status immediately switches to "Closed" with no loading indicator. The open state never seems to complete though. 

<img width="138" alt="image" src="https://user-images.githubusercontent.com/1500721/142295606-4db9da26-2c4b-4055-8f8b-488e84b615d1.png">

**Comment by iKrushYou** [comment]
<img width="134" alt="image" src="https://user-images.githubusercontent.com/1500721/142296472-e6233cab-a6bf-4cac-8e44-b786c0e585cb.png">
Now it's reversed. Is there any sort of debug logging I can enable?

**Comment by QuickSander** [comment]
Hi, you could enable DEBUG logging in Homebridge's setting.
This will aid me a lot in seeing what's going on. Since you do not specify a state retrieval and target position I need to see if the plugin correctly updates the cache.

**Comment by QuickSander** [comment]
The behaviour of HomeKit was: when targetPos != currentPos -> opening/closing. It would always ignore the state. I think that is still the case, but it would be nice if you can post the DEBUG logging. I myself namely let my curtain return all these variables and therefor are not struck by what you experience.

**Comment by QuickSander** [comment]
Please also remove all attributes that you do not use, I'm not sure yet, but supplying only "method" for certain properties might make the plugin think you specified an empty URL (while your intention is to ignore it).

**Comment by QuickSander** [comment]
No answer, closing issue.

**Comment by iKrushYou** [comment]
> No answer, closing issue.

Hey, sorry I didn’t see the original comments only this one

my homebridge server actually just died so once I recover that I’ll do so report back
